name: publish

on: [push]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: yarn run lint
      - name: install
        run: npm install
      - name: test
        run: npm test
      - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.TOKEN }}
